apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gitea
    app.kubernetes.io/instance: gitea
    app.kubernetes.io/name: gitea
    app.kubernetes.io/version: 1.20-nightly
    version: 1.20-nightly
  name: gitea
  namespace: tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: gitea
      app.kubernetes.io/name: gitea
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: gitea
        app.kubernetes.io/instance: gitea
        app.kubernetes.io/name: gitea
        app.kubernetes.io/version: 1.20-nightly
        version: 1.20-nightly
    spec:
      containers:
      - image: gitea/gitea:1.20-nightly-rootless
        imagePullPolicy: Always
        name: gitea
        ports:
        - containerPort: 2222
          name: ssh
        - containerPort: 3000
          name: http
        resources:
          limits:
            cpu: "2.0"
            memory: 2Gi
          requests:
            cpu: "1.0"
            memory: 512Mi
        volumeMounts:
        - mountPath: /etc/gitea
          name: data
          subPath: config
        - mountPath: /var/lib/gitea
          name: data
          subPath: data
      securityContext:
        fsGroup: 1000
      terminationGracePeriodSeconds: 60
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: gitea-data-claim
