apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - envFrom:
            - secretRef:
                name: postgres-secrets
            - configMapRef:
                name: postgres-configmap
          image: postgres:12.4-alpine
          name: postgres
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/pgsql/data
              name: gitea-database-volume
          resources:
            requests:
              memory: "1Gi"
              cpu: ".5"
            limits:
              memory: "2Gi"
              cpu: "1.0"
      volumes:
        - name: gitea-database-volume
          persistentVolumeClaim:
            claimName: gitea-database-volume-claim
