apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-agent
  namespace: argocd
spec:
  project: monitoring
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: grafana-agent
      targetRevision: 0.13.0
      helm:
        releaseName: grafana-agent
        includeCRDs: true
        valueFiles:
          - $values/manifests/monitoring/values/grafana-agent.yaml
    - repoURL: git@github.com:matt328/bootstrap
      targetRevision: HEAD
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
