namespace: monitoring
helmCharts:
  - name: mimir-distributed
    version: 4.4.1
    repo: https://grafana.github.io/helm-charts
    releaseName: mimir
    namespace: monitoring
    valuesFile: mimir-values.yaml
