apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: alloy
    repo: https://grafana.github.io/helm-charts
    version: 1.1.2
    releaseName: alloy
    namespace: management
    valuesFile: values.yaml

configMapGenerator:
  - name: alloy
    files:
      - config.alloy
    options:
      disableNameSuffixHash: true
