apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-echo-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-echo
  template:
    metadata:
      labels:
        app: nginx-echo
    spec:
      containers:
        - name: nginx-echo
          image: nginxinc/nginx-hello:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-echo-service
spec:
  selector:
    app: nginx-echo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
