apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - namespace.yaml
  - github.com/argoproj/argo-cd/manifests/cluster-install?ref=v2.7.6
  - traefik-ingress.yaml
  - sealed-secret.yaml

patches:
  - path: overlays/cmd-params-cm.yaml
  - path: overlays/argocd-cm.yaml
