apiVersion: v1
kind: Service
metadata:
  labels:
    app: argocd
  name: argocd
  namespace: argocd
spec:
  type: LoadBalancer
  ports:
    - name: argocd-server
      port: 80
      protocol: TCP
      targetPort: 3000
    - name: gitea-ssh
      port: 22
      protocol: TCP
      targetPort: 2222
  selector:
    app: gitea
