namespace: monitoring
helmCharts:
  - name: grafana
    version: 6.56.2
    repo: https://grafana.github.io/helm-charts
    releaseName: grafana
    namespace: monitoring
    valuesFile: grafana-values.yaml

resources:
  - namespace.yaml
  - ingress-route.yaml
  - sealed-secret.yaml
