apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAtYoxFSbayZ5YyCrkFDMP/QBon5LdtFtVt6fTb+aESw+dKJb8U5jDW7sn8CA4Z15sPTxCXDjGDk0lYo4DyCzJQrk7hIR1U+AVtsinaR2jgQDNJyyTwib/G646zObgU+Cr5AqFRDKIkEnHbj99c1NPjuNhidgoJqncQ0QHdPKLqdGFO/hU7t/Fkb633yeRUgAKsyHj3OgT5x/oSwoHf9Uivfc0iaKk2zV9XJ+lfP35V0U1FTQKUvh+rOyuPitLprarGLIWeI2Y/TqdWr4nIAJuJhgcHZqjgMBj3bgTl58C94Zyy87qsVnSqN5OTH+DE8Rv7BmHRpWfAu8lXFyUYq7rMbyxtg/qLwfTQyqgu3qLajdbslwTgZcir488upI2pHhjQODNaXqkPH0FkBEIz4JZ87HS3auGy0nFlvZR3lL0wPjDO0TV1Hn253CJnBU8FxEWrgW2Mkr30GHFBcVAO2crhzJJlAv6pZHchehDlYlD2Q6F4CY17YCx/ubnZNtk2FsXHhZagGQH2ZQPwGa/KOr4wJYw1GUrzWXGEchfVfjTQi/pjJDBvnUebswakNw5hib7BOFyD50VhGpvvRtOURj1xO0dJoO6oF1paOTGg2HGwpXCV9G570D3IBPJJAWY5z4ygMI63Sv3N0qD+gp2zqCy4MjZW03OuMp0RJLkHxuHFHffhtQzusJ3kvtJxlAKIufBOhaIea8n7
    admin-user: AgBdRmD8a56rkCw3kyBVBb7SjmvRRb56eeYQo3FdxihGn2VpRxwiSLSpwI17tNyJDHLOpgMEEnKa1Q8llj6gNP2LH7cWjieukS/JLpQ2E931npVHu3tt4IaI5urPQuIGEeI0HQbL9dpesVeFqUdRvHSuPMGJslvxwUiL/CuIf9w6tFFU3jQ4r4srxyzidP+V6VDJRfF9NygRhItMdnBjwDEj5e50TpVB+iwEBwhiFLkud0GmtRYLJyQEEVG67ZlxYzzSY9Pf83aVzIxSBtc7bCq45ha/31M/lUjvu+U3UODXsnQF9aK/zhdFWr+mM2gxz5RZnNSIlKen7D+vblGj+RG4Ab+LRVmEQzK4SMUAS80y2iMHSiBgeTpysOHh7nv3/F5bUpNbHfvX+6CnNHFad75JC1JaB+tzMs2pctzvo0GU/jkJ6zdzscv8zQZCmlngOEJmCB7xNEcs/7K8TQnOZoVo91eljmlULJs6WcGl1J9oWArQTg5VfjRaOVkNVY3NKG0bWtPGMCq8pZ+nJam7zYuuoZV4ZIDl2HJvaDuZ2tmZvSbXv8UUYhiutLHq7cIkM/P0icDHFT2rpmJ4GH61/ZL+ypsTHRWQGJMj/4P7gUInZhBRHBSB+xb6lXxA3MSh/Nw4hiCQNkdlMxbDM8qbDO7D15GsdlaCDdtjH6HT1dQJEuuzznSadYHxpn306E/fnCT67eC3EXmd
  template:
    metadata:
      creationTimestamp: null
      name: grafana
      namespace: monitoring

