apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-state-metrics
  namespace: argocd
spec:
  project: monitoring
  source:
    chart: kube-state-metrics
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 5.6.1
    helm:
      releaseName: kube-state-metrics
      values: |
        prometheusScrape: false
        selfMonitor:
          enabled: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
