apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-agent
  namespace: argocd
spec:
  project: monitoring
  source:
    chart: grafana-agent
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 0.13.0
    helm:
      releaseName: grafana-agent
      includeCRDs: true
      valueFiles:
        - grafana-agent-values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
