apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgC/6B5VQNtFtAXNWBaYBIDPsSBJuaDhHxhKeQt7GWGa2TJ5+kiWw3rM6UUzKPJ5RqKt7mGWq4pq75R7Y/DhzcHDs7Yxj+K8d+kwm/GxjVinHJhce7zMnALS1zAzTxcRNEtdGKJR99z/OxFMOg+07g5sm7GPXVTKBjO4rL8VPr7aGqpg7KLfvJBmS7ZGjb68p1VNhMFxiXBorc8SPLyQUErNjzjjIC14PEnqmgvSOyLAfRJLSqNaVlEDDC0Ei6RaAt2Yy6nnvxpDOTultxSQOffsYyzRaJ+5K5ggcIvw+OP6lqEp44bqbyU0y5oe7FYhKsBGHZ8JhSzLxeFCUiM67HS+i2EctHiu5VRBH6NQnr0s2lfnVyi+JF5CuBSN4b9jz+76wa/kQqt2oECbn8kQZcsOdyHAMyLenWIaatHkVs4mtNRrscNCTXxfupePLSgefPR/+SE8DVc4x6liRHmbCxFn/5v18ZsFladCZc5OyH+Q5bmzGJi04jdoU2jbA/wfThHqqGfq/i9BULwom6Gt/bBY8fd8I6ATFO0FJnxbwifQO+TZJ6sgTW0RY0mSn2A7VO6mYZRY0kMtxKiIlEMZqyRU6WbAUda28lEa1jTA22Rxj8sGXI/NBxi3QJZT6JE590gTGTkTnQnNdctkI/4R+DrZPU7Xr9zvW4BoF9aJXSuvg1AJh/QgLEXSs6Dh2rTAi5Av5HbTqa5i
    admin-user: AgCbNJyavV3c0ilfaYyfhsVqE+s2FlbGkaRLwN6h9CgMU/2Ua4bb7UTrWfDVPeNUdahUNWPFkthY/eLT3JgVxMZiaLOybcQ853zAf9WFh701s4ytLZdtyw4JfUfgtI5USMKSGgpD0kOfaQA0UYlMr+mHyAnl0VPLzcl6LoXmYXt78KlbivqOSzvuWB6gztctLiPfZ/C3023lqFbqFqQy6bKXtx5YLfsgt/U3fTIVBgOAFKLWl2XieE46wiJTe7prXbeVHhRzBIOU5ehtHFB301W26K3/p4kqdghJUay46+a5lSk/YGTu1U+SPCwC+vvjIVLz08Ta+0JxzFyqmnyZbEX/sE0cltve0+WIQAHrqPLUNvXb/pJxWSXBzFMxorL6mCS2Ch9raP6N4hXpjt+q2Sx/YOxu2Qlcwm9LLpJkn12Jm44cF1XFwhJMK5kTmEJ5WRnw9ZiGGzMnj6QTkpvQuqV0fNKyfK5V0zbbojv6SQLWLsiTFufEc3y5iI/n6621b+GTO+W1rZnEHkPVmIqQ5TENifRBp+gMlbo+LTPh9R7ckuvMGH/U0+d/7itogudmK33zVX1Pa+mgWqHsGsue6zQvgZTNyMh95cun4/xmnV+j91MZiI18ZjX7fH5b1qVL9P+kVvMBykmSdBg65NzPjRrPSrSA0G4pQ2RGvtFOxGbILSF+jWz06YC7lmRRB5nQm24hPuTyO0vR
  template:
    metadata:
      creationTimestamp: null
      name: grafana
      namespace: monitoring

