apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argocd
  namespace: argocd
spec:
  description: "ArgoCD Project"
  sourceRepos:
    - "https://github.com/matt328/bootstrap.git"
  destinations:
    - name: swe-dev
      namespace: argocd
      server: "https://kubernetes.default.svc"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-app
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: argocd
  source:
    directory:
      recurse: true
    path: deployments
    repoURL: https://github.com/matt328/bootstrap.git
    targetRevision: HEAD
