apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:matt328/bootstrap
    targetRevision: HEAD
    path: manifests/argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
