apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/matt328/bootstrap
    targetRevision: HEAD
    path: manifests/gitea
  destination:
    server: https://kubernetes.default.svc
    namespace: gitea
