apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-root
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: git@github.com:matt328/bootstrap
      targetRevision: HEAD
      path: monitoring-apps
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
# TODO: make this an ApplicationSet
