apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tools-root
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:matt328/bootstrap
    targetRevision: HEAD
    path: tools-apps
  destination:
    server: https://kubernetes.default.svc
    namespace: tools
