apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tools
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/matt328/bootstrap
        revision: main
        directories:
          - path: manifests/tools/*
  template:
    metadata:
      name: "{{path.basename}}"
    spec:
      project: "tools"
      source:
        repoURL: https://github.com/matt328/bootstrap
        targetRevision: main
        path: "{{path}}"
        plugin:
          name: kustomize-enable-helm
      destination:
        server: https://kubernetes.default.svc
        namespace: "*"
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - FailOnSharedResource=true
