apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-echo-server
  namespace: argocd
spec:
  project: prod
  source:
    repoURL: https://github.com/matt328/bootstrap
    targetRevision: HEAD
    path: "manifests-cluster2/nginx"
  destination:
    server: https://192.168.50.113:6443
    namespace: prod
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
