apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-echo-server
  namespace: argocd
spec:
  project: prod
  source:
    repoURL: https://github.com/nginxinc/docker-nginx-hello
    targetRevision: HEAD
    path: ""
  destination:
    server: https://192.168.50.113:6443
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
