agent:
  clustering:
    enabled: true
  configMap:
    create: true
    name: grafana-agent
    key: fow-config.river
  mounts:
    varlog: true
    dockercontainers: true
    extra:
      - mountPath: /host/root
        name: rootfs
      - mountPath: /host/sys
        name: sysfs
      - mountPath: /host/proc
        name: procfs
controller:
  type: statefulset
  enableStatefulSetAutoDeletePVC: true
  replicas: 3
  volumes:
    extra:
      - hostPath:
          path: /
        name: rootfs
      - hostPath:
          path: /sys
        name: sysfs
      - hostPath:
          path: /proc
        name: procfs
ingress:
  enabled: true
