apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAtmsd5Ptrj4fjXAP3uI0fYCA7aL+nNkbstF+cZXJ2vZthowFUMT663B4Y9A/8ekJd8FPHQwQJl3sXjRuW0/SD99I6cP0gWTafEWJWYf24mSMJsmo65B/vCGAdoc5Ts5RZvj0CqWirCDvNU6LhJ0PgYVOH5rXbfAL0dYydbRkdAFL8ts211MjPXGZc70MDrYHYZYFDStqW3MHezJ2AQlEmV3a51GsbX4bkU3mArX+9vxSit8Lxf2o9NfUkQzLN7aVy6+y9njwGN+D09g/t/UhIG0TluSVy/ONwR9ajVZryGryD8LsYdbduJURQl+sRWmqM76vXiTRHRU1dBJFW8LNxKvj6GnI8NG/RET9an/osU1uwGOUQ5lw3PGA4DR19muLsxs0t4VRo9r9wBrK9Io3k/ZJkYC+UpKbzWhRijw4j5Wpcv+56iLmSjzxpsr+aXFK0YfQqV866i5yL7l2ORI76yIwRM9snJWDwYfsHystypEPwHa25lU/+BNFS45JQOBIRi17eaue7Ts3nRnyeYuqphB5tp8RBQ7bkVLafj4W4wQxKFl1uAqn9pbADNzPAnmpQYldEZGiNnXrxoHu3rHOPevRB4B5BeChmEKwzauDVUXvxIvT+q9qCWJscbh4XxFpoARQE8FQe7633XayQtTSZFpgqqxLA3rwjgzPjEuTuUYw9ela7TIcpXdDz895lLDiQN7tbJnIj0
    admin-user: AgCOEFPs2v/tPPVEuX6UwDwSPvcC+mHDOu+EKzyuvqZ73QDVb3PsiZviEVebfpP+Se8pZzPcdcrSbTn7zvWVkXqjU89saBhyEMWt5+3x/Iw0xWAc+MV2FTtdaUBtmaUI85MFal9Stp39Xla/2vQORqIEHthhk+ZCYdmK4K60/5H7xvb171iG/DcEKEZLGjZ7U7MpJUcuSIJkeo1xdz9MhQZ0LiQCZf6lbV1gvvGyGWBfketqCY7R9MeSh8wyY0+dQOs9vNirHwrvISnjo7jjK1QORMYVWsHMz5UWiMTgzSvKumtv1m5bmQo69FxNWM+/IwEvQeC3v/A9+dniD2ktwf4LZwztC03na/NB3KxKsnbjWk5C87oa2CxhbkyGiVGy4IY4r0zTjdOJlSuNsi/uZzZCeLxD/82GJeZHQAKsXdYiBbi8xsaeqCHeln8qG5dOxEHpbO/t8EdZZrH5nvbVFTBC77JUvvY6cLQbHuWpRoVxmu94bitU6ueNZ6P2/fnwmldcUBjgKEBoNyTpN0b9klLe5BNysHBlB2zvQO/bzjV7Y7APfMazRpNTIS4ccev40QdxKgqSoCdkbf641fVfyTk9lNnk3yOvRR53zOb5ZTVPOb2t9jMgW+CXvPpF628/fk0nDnsPJy6F9JMkGxieEKicANwNr1sLDTXBkeC7dWG92ekhvpUTQhtsFc84/9KoVUtOmDakL1R/
  template:
    metadata:
      creationTimestamp: null
      name: grafana
      namespace: monitoring

