apiVersion: v1
kind: Service
metadata:
  labels:
    app: argocd
  name: argocd
  namespace: management
spec:
  type: LoadBalancer
  ports:
    - name: server
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: argocd-server
