redis-cluster:
  enabled: false
postgresql:
  enabled: true
postgresql-ha:
  enabled: false

persistence:
  enabled: false

gitea:
  config:
    server:
      ROOT_URL: http://gitea.home
      DOMAIN: gitea.home
      PROTOCOL: http
    database:
      DB_TYPE: postgres
      HOST: gitea-postgresql
      NAME: gitea
      USER: gitea
      PASSWD: gitea
    session:
      PROVIDER: memory
    cache:
      ADAPTER: memory
    queue:
      TYPE: level
